In [1]:
import pandas as pd

### Getting data from `inputf.in`
Converting it into a list of words, stripped of all whitespaces

In [2]:
with open('inputf.in') as f:
    data = f.read().split()       
data.append('xxxxx')

### Parsing the required data from the list of words, and store them in the form of different dicts.

persons:
    
    key = enrollment_no
    
    'n' : name
    
    'c' : college
    
    'e' : enrollment_no
    
    's' : class_no
    
    'b' : batch
    
    'z' : course_code
    
courses:

    key = course_code

    'c' : course code
    
    'n' : course name
    
subjects:
    
    key = subject_code
    
    'n' : name
    
    'v' : credits
    
    's' : semester number
    
entries:
    
    key = enrollment_no
    
    'm' : semester
    
    'u' : subject_code
    
    'n' : internal
    
    'x' : external
    
    't' : total
    
    'f' : type (REGULAR / REAPPEAR)

In [3]:
c_institute = ''
c_course_code = '' 
c_course_name = '' 
c_enrollment_no = ''

c_sem = ''
c_type = ''
c_batch = ''

persons = {}
courses = {}
subjects = {}
entries = {}
college_list = {
    'Ambedkar Institute Of Advanced Communication Technologies & Research (Formerly Ait)' : 'AIACTR', 
    'Amity School Of Engineering & Technology' : 'ASET',
    'Bhagwan Mahaveer College Of Engineering & Management' : 'BMCEM',
    'Bhagwan Parshuram Institute Of Technology' : 'BPIT',
    'Bharati Vidyapeeth College Of Engineering' : 'BVCOE',
    'Bm Institute Of Engineering & Technology' : 'BMIET',
    'Delhi Technical Campus, Greater Noida' : 'DTC',
    'Dr. Akhilesh Das Gupta Institute Of Technology And Management (Formerly Niec)' : 'ADGITM',
    'Dr. Akhilesh Das Gupta Institute Of Technology And Management(Formerly Niec)' : 'ADGITM',
    'G B Pant Govt. Engineering College' : 'GBPGEC',
    'Guru Tegh Bahadur Institute Of Technology' : 'GTBIT',
    'Hmr Institute Of Technology & Management' : 'HMRITM',
    'Jims Engineering Management Technical Campus, Greater Noida' : 'JIMS',
    'Maharaja Agrasen Institute Of Technology' : 'MAIT',
    'Maharaja Surajmal Institute Of Technology' : 'MSIT',
    'Mahavir Swami Institute Of Technology' : 'MASW',
    'Northern India Engineering College' : 'ADGITM'
}

for x in range(len(data)):
    
    if data[x]=='Institution:' :
        sub = ''
        x+=1
        while data[x] != 'S.No.' and data[x] != 'CS/Remarks':
            sub += ' ' + data[x]
            x+=1
        c_institute = college_list[sub.strip().title()]
        
    elif len(data[x]) == 7 and data[x][:2] == 'ET':
        sub = ''
        x-=1
        while 1:
            sub += ' ' + data[x]
            x+=1 
            if data[x] in ['1','2','3','4']:
                sub += ' ' + data[x]
                break
        inp = sub.strip().split()
        if inp[0] not in subjects:
            subjects[inp[0]] = {
                'n' : ' '.join(inp[2:-1]).title(), # subject_name
                'v' : int(inp[-1]),
                's' : int(c_sem)
            }
    
    elif len(data[x]) == 11 and data[x].isdigit() :
        sub = ''
        while data[x] != 'SID:':
            sub += ' ' + data[x]
            x+=1
        inp = sub.strip().split()
        c_enrollment_no = inp[0]
        if inp[0] not in persons:
            persons[inp[0]] = {
                'n' : ' '.join(inp[1:]), # name
                'c' : c_institute, # college
                'e' : int(c_enrollment_no), # enrollment_no
                's' : int(c_enrollment_no[3:6]), # class_no
                'b' : int(c_batch), # batch
                'z' : int(c_course_code) # course_code
            }
            
    elif len(data[x]) == 8 and data[x].find('(') != -1 and data[x].find(')') != -1 :
        sub = ' '.join(data[x:x+4])
        x+=4
        inp = sub.strip().split()
        for x in range(len(inp)):
            if inp[x][0] in ['A','B','C','D','-']:
                inp[x] = '0'
        entries.setdefault(c_enrollment_no, []).append({
            'm' : int(c_sem), # semester
            'u' : inp[0][:-3], # subject_code
            'n' : int(inp[1]), # internal
            'x' : int(inp[2]), # external
            't' : int(inp[3].split('(')[0]), # total
            'f' : (c_type == 'REGULAR') # type
        })

    elif data[x]=='Sem./Year:' :
        c_sem = int(data[x+1])
        x+=1

    elif data[x]=='Examination:' :
        c_type = data[x+1]
        x+=1
    
    elif data[x]=='Programme' :
        d = data[x+1]
        if d == 'Code:':
            c_course_code = data[x+2]
        else :
            sub = ''
            x+=1
            while 1 :
                sub += data[x] + ' '
                if data[x][-1] == ')':
                    break;
                x+=1
            courses[c_course_code] = sub.strip().title()
    
    elif data[x]=='Batch:' :
        c_batch = data[x+1]
        x+=1

In [13]:
persons['03111502716']

{'n': 'SHARAT SACHIN',
 'c': 'BVCOE',
 'e': 3111502716,
 's': 115,
 'b': 2016,
 'z': 27}

In [5]:
courses

{'027': 'Name: Bachelor Of Technology (Computer Science And Engineering)'}

In [6]:
subjects

{'99101': {'n': 'Applied Mathematics-1', 'v': 4, 's': 1},
 '99103': {'n': 'Applied Physics-1', 'v': 3, 's': 1},
 '36105': {'n': 'Manufacturing Processes', 'v': 3, 's': 1},
 '49107': {'n': 'Electrical Technology', 'v': 3, 's': 1},
 '98109': {'n': 'Human Values And Professional Ethics-1', 'v': 1, 's': 1},
 '27111': {'n': 'Fundamentals Of Computing', 'v': 2, 's': 1},
 '99113': {'n': 'Applied Chemistry', 'v': 3, 's': 1},
 '99151': {'n': 'Applied Physics Lab-1', 'v': 1, 's': 1},
 '49153': {'n': 'Electrical Technology Lab', 'v': 1, 's': 1},
 '36155': {'n': 'Workshop Practice', 'v': 2, 's': 1},
 '27157': {'n': 'Fundamentals Of Computing Lab', 'v': 1, 's': 1},
 '36157': {'n': 'Engineering Graphics Lab', 'v': 2, 's': 1},
 '99161': {'n': 'Applied Chemistry Lab', 'v': 1, 's': 1},
 '99102': {'n': 'Applied Mathematics-2', 'v': 4, 's': 2},
 '99104': {'n': 'Applied Physics-2', 'v': 3, 's': 2},
 '28106': {'n': 'Electronic Devices', 'v': 3, 's': 2},
 '27108': {'n': 'Introduction To Programming', 'v': 3, 's': 2},
 '36110': {'n': 'Engineering Mechanics', 'v': 3, 's': 2},
 '98112': {'n': 'Communications Skills', 'v': 3, 's': 2},
 '56114': {'n': 'Environmental Studies', 'v': 3, 's': 2},
 '99152': {'n': 'Applied Physics Lab-2', 'v': 1, 's': 2},
 '27154': {'n': 'Programming Lab', 'v': 1, 's': 2},
 '28156': {'n': 'Electronic Devices Lab.', 'v': 1, 's': 2},
 '36158': {'n': 'Engineering Mechanics Lab', 'v': 1, 's': 2},
 '56160': {'n': 'Environmental Studies Lab', 'v': 1, 's': 2},
 '99201': {'n': 'Applied Mathematics-3', 'v': 4, 's': 3},
 '27203': {'n': 'Foundation Of Computer Science', 'v': 4, 's': 3},
 '28205': {'n': 'Switching Theory And Logic Design', 'v': 4, 's': 3},
 '49207': {'n': 'Circuits And Systems', 'v': 4, 's': 3},
 '27209': {'n': 'Data Structure', 'v': 4, 's': 3},
 '27211': {'n': 'Computer Graphics And Multimedia', 'v': 4, 's': 3},
 '28253': {'n': 'Switching Theory And Logic Design Lab', 'v': 1, 's': 3},
 '27255': {'n': 'Data Structure Lab', 'v': 1, 's': 3},
 '27257': {'n': 'Computer Graphics And Multimedia Lab', 'v': 1, 's': 3},
 '49257': {'n': 'Circuits And Systems Lab', 'v': 1, 's': 3},
 '99202': {'n': 'Applied Mathematics-4', 'v': 4, 's': 4},
 '27204': {'n': 'Computer Organization And Architecture', 'v': 4, 's': 4},
 '27206': {'n': 'Theory Of Computation', 'v': 4, 's': 4},
 '27208': {'n': 'Database Management Systems', 'v': 4, 's': 4},
 '27210': {'n': 'Object Oriented Programming', 'v': 3, 's': 4},
 '28212': {'n': 'Communication Systems', 'v': 4, 's': 4},
 '99250': {'n': 'Ncc/Nss', 'v': 1, 's': 4},
 '99252': {'n': 'Applied Mathematics Lab', 'v': 1, 's': 4},
 '27254': {'n': 'Computer Organization And Architecture Lab', 'v': 1, 's': 4},
 '27256': {'n': 'Database Management Systemslab', 'v': 1, 's': 4},
 '28256': {'n': 'Communication Systems Lab', 'v': 1, 's': 4},
 '27258': {'n': 'Object Oriented Programming Lab', 'v': 1, 's': 4},
 '27301': {'n': 'Algorithms Design And Analysis', 'v': 4, 's': 5},
 '98301': {'n': 'Communication Skills For Professionals', 'v': 1, 's': 5},
 '27303': {'n': 'Software Engineering', 'v': 4, 's': 5},
 '28303': {'n': 'Digital Communication', 'v': 4, 's': 5},
 '27307': {'n': 'Java Programming', 'v': 4, 's': 5},
 '99311': {'n': 'Industrial Management', 'v': 3, 's': 5},
 '27351': {'n': 'Algorithms Design And Analysis Lab', 'v': 1, 's': 5},
 '98351': {'n': 'Communication Skills For Professionals Lab', 'v': 1, 's': 5},
 '27353': {'n': 'Software Engineering Lab', 'v': 1, 's': 5},
 '27357': {'n': 'Java Programming Lab', 'v': 1, 's': 5},
 '28357': {'n': 'Digital Communication Lab', 'v': 1, 's': 5},
 '27359': {'n': 'Viva Industrial Training / In - House Workshop',
  'v': 1,
  's': 5},
 '27302': {'n': 'Compiler Design', 'v': 4, 's': 6},
 '27304': {'n': 'Operating Systems', 'v': 4, 's': 6},
 '27306': {'n': 'Computer Networks', 'v': 4, 's': 6},
 '27308': {'n': 'Web Technology', 'v': 3, 's': 6},
 '27310': {'n': 'Artificial Intelligence', 'v': 4, 's': 6},
 '49310': {'n': 'Microprocessor And Microcontroller', 'v': 4, 's': 6},
 '27352': {'n': 'Operating Systems(Linux Programming And Administration) Lab',
  'v': 1,
  's': 6},
 '27354': {'n': 'Computer Networks Lab', 'v': 1, 's': 6},
 '27356': {'n': 'Web Technology Lab', 'v': 1, 's': 6},
 '49358': {'n': 'Microprocessor And Microcontroller Lab', 'v': 1, 's': 6}}

In [7]:
entries['03111502716']

[{'m': 1, 'u': '99101', 'n': 22, 'x': 61, 't': 83, 'f': True},
 {'m': 1, 'u': '99103', 'n': 24, 'x': 48, 't': 72, 'f': True},
 {'m': 1, 'u': '36105', 'n': 21, 'x': 48, 't': 69, 'f': True},
 {'m': 1, 'u': '49107', 'n': 19, 'x': 37, 't': 56, 'f': True},
 {'m': 1, 'u': '98109', 'n': 0, 'x': 86, 't': 86, 'f': True},
 {'m': 1, 'u': '27111', 'n': 21, 'x': 55, 't': 76, 'f': True},
 {'m': 1, 'u': '99113', 'n': 23, 'x': 55, 't': 78, 'f': True},
 {'m': 1, 'u': '99151', 'n': 37, 'x': 56, 't': 93, 'f': True},
 {'m': 1, 'u': '49153', 'n': 35, 'x': 46, 't': 81, 'f': True},
 {'m': 1, 'u': '36155', 'n': 37, 'x': 44, 't': 81, 'f': True},
 {'m': 1, 'u': '27157', 'n': 37, 'x': 48, 't': 85, 'f': True},
 {'m': 1, 'u': '36157', 'n': 38, 'x': 46, 't': 84, 'f': True},
 {'m': 1, 'u': '99161', 'n': 36, 'x': 53, 't': 89, 'f': True},
 {'m': 2, 'u': '99102', 'n': 17, 'x': 65, 't': 82, 'f': True},
 {'m': 2, 'u': '99104', 'n': 21, 'x': 71, 't': 92, 'f': True},
 {'m': 2, 'u': '28106', 'n': 19, 'x': 72, 't': 91, 'f': True},
 {'m': 2, 'u': '27108', 'n': 21, 'x': 65, 't': 86, 'f': True},
 {'m': 2, 'u': '36110', 'n': 22, 'x': 63, 't': 85, 'f': True},
 {'m': 2, 'u': '98112', 'n': 20, 'x': 65, 't': 85, 'f': True},
 {'m': 2, 'u': '56114', 'n': 20, 'x': 61, 't': 81, 'f': True},
 {'m': 2, 'u': '99152', 'n': 37, 'x': 54, 't': 91, 'f': True},
 {'m': 2, 'u': '27154', 'n': 36, 'x': 54, 't': 90, 'f': True},
 {'m': 2, 'u': '28156', 'n': 37, 'x': 57, 't': 94, 'f': True},
 {'m': 2, 'u': '36158', 'n': 39, 'x': 44, 't': 83, 'f': True},
 {'m': 2, 'u': '56160', 'n': 37, 'x': 57, 't': 94, 'f': True},
 {'m': 3, 'u': '99201', 'n': 21, 'x': 24, 't': 45, 'f': True},
 {'m': 3, 'u': '27203', 'n': 22, 'x': 61, 't': 83, 'f': True},
 {'m': 3, 'u': '28205', 'n': 19, 'x': 51, 't': 70, 'f': True},
 {'m': 3, 'u': '49207', 'n': 20, 'x': 51, 't': 71, 'f': True},
 {'m': 3, 'u': '27209', 'n': 24, 'x': 54, 't': 78, 'f': True},
 {'m': 3, 'u': '27211', 'n': 17, 'x': 46, 't': 63, 'f': True},
 {'m': 3, 'u': '28253', 'n': 34, 'x': 53, 't': 87, 'f': True},
 {'m': 3, 'u': '27255', 'n': 36, 'x': 53, 't': 89, 'f': True},
 {'m': 3, 'u': '27257', 'n': 35, 'x': 48, 't': 83, 'f': True},
 {'m': 3, 'u': '49257', 'n': 37, 'x': 41, 't': 78, 'f': True},
 {'m': 4, 'u': '99202', 'n': 17, 'x': 60, 't': 77, 'f': True},
 {'m': 4, 'u': '27204', 'n': 20, 'x': 52, 't': 72, 'f': True},
 {'m': 4, 'u': '27206', 'n': 23, 'x': 55, 't': 78, 'f': True},
 {'m': 4, 'u': '27208', 'n': 20, 'x': 55, 't': 75, 'f': True},
 {'m': 4, 'u': '27210', 'n': 22, 'x': 42, 't': 64, 'f': True},
 {'m': 4, 'u': '28212', 'n': 20, 'x': 41, 't': 61, 'f': True},
 {'m': 4, 'u': '99250', 'n': 0, 'x': 83, 't': 83, 'f': True},
 {'m': 4, 'u': '99252', 'n': 37, 'x': 48, 't': 85, 'f': True},
 {'m': 4, 'u': '27254', 'n': 32, 'x': 48, 't': 80, 'f': True},
 {'m': 4, 'u': '27256', 'n': 33, 'x': 53, 't': 86, 'f': True},
 {'m': 4, 'u': '28256', 'n': 37, 'x': 48, 't': 85, 'f': True},
 {'m': 4, 'u': '27258', 'n': 34, 'x': 50, 't': 84, 'f': True},
 {'m': 5, 'u': '27301', 'n': 19, 'x': 47, 't': 66, 'f': True},
 {'m': 5, 'u': '98301', 'n': 23, 'x': 55, 't': 78, 'f': True},
 {'m': 5, 'u': '27303', 'n': 17, 'x': 68, 't': 85, 'f': True},
 {'m': 5, 'u': '28303', 'n': 19, 'x': 66, 't': 85, 'f': True},
 {'m': 5, 'u': '27307', 'n': 24, 'x': 50, 't': 74, 'f': True},
 {'m': 5, 'u': '99311', 'n': 24, 'x': 51, 't': 75, 'f': True},
 {'m': 5, 'u': '27351', 'n': 37, 'x': 45, 't': 82, 'f': True},
 {'m': 5, 'u': '98351', 'n': 32, 'x': 50, 't': 82, 'f': True},
 {'m': 5, 'u': '27353', 'n': 37, 'x': 50, 't': 87, 'f': True},
 {'m': 5, 'u': '27357', 'n': 34, 'x': 54, 't': 88, 'f': True},
 {'m': 5, 'u': '28357', 'n': 34, 'x': 50, 't': 84, 'f': True},
 {'m': 5, 'u': '27359', 'n': 32, 'x': 52, 't': 84, 'f': True},
 {'m': 6, 'u': '27302', 'n': 19, 'x': 69, 't': 88, 'f': True},
 {'m': 6, 'u': '27304', 'n': 22, 'x': 50, 't': 72, 'f': True},
 {'m': 6, 'u': '27306', 'n': 19, 'x': 60, 't': 79, 'f': True},
 {'m': 6, 'u': '27308', 'n': 21, 'x': 61, 't': 82, 'f': True},
 {'m': 6, 'u': '27310', 'n': 22, 'x': 52, 't': 74, 'f': True},
 {'m': 6, 'u': '49310', 'n': 16, 'x': 51, 't': 67, 'f': True},
 {'m': 6, 'u': '27352', 'n': 37, 'x': 52, 't': 89, 'f': True},
 {'m': 6, 'u': '27354', 'n': 35, 'x': 58, 't': 93, 'f': True},
 {'m': 6, 'u': '27356', 'n': 37, 'x': 52, 't': 89, 'f': True},
 {'m': 6, 'u': '49358', 'n': 37, 'x': 55, 't': 92, 'f': True}]

In [8]:
studentwise = []
for x in persons:
    student = {}
    student['en_no'] = x
    student['name'] = persons[x]['n'].title()
    student['college'] = persons[x]['c']
    student['batch'] = persons[x]['b']
    student['class'] = persons[x]['s']
    student['course'] = persons[x]['z']
    tot,totw,ns,nsw = [0]*9,[0]*9,[0]*9,[0]*9
    num_sems = set()

    for y in [1,2,3,4,5,6,7,8]:
        for z in entries[x]:
            if z['m'] == y:
                num_sems.add(y)
                student[z['u']] = (z['n'], z['x'], z['t'])
                tot[y] += z['t']
                ns[y] += 1
                totw[y] += z['t'] * subjects[str(z['u'])]['v']
                nsw[y] += subjects[str(z['u'])]['v']
                
    student['sems'] = list(num_sems)
    for y in [1,2,3,4,5,6,7,8]:
        student['tot'+str(y)] = tot[y]
        student['totw'+str(y)] = totw[y]
        student['ns'+str(y)] = ns[y]
        student['nsw'+str(y)] = nsw[y]
    studentwise.append(student)

In [9]:
studentwise[2000]

{'en_no': '00815607217',
 'name': 'Udisha Gupta',
 'college': 'ADGITM',
 'batch': 2016,
 'class': 156,
 'course': 27,
 '99201': (19, 43, 62),
 '27203': (20, 61, 81),
 '28205': (24, 32, 56),
 '49207': (17, 54, 71),
 '27209': (21, 67, 88),
 '27211': (19, 54, 73),
 '28253': (36, 57, 93),
 '27255': (37, 48, 85),
 '27257': (32, 53, 85),
 '49257': (32, 52, 84),
 '99202': (24, 34, 58),
 '27204': (21, 55, 76),
 '27206': (23, 48, 71),
 '27208': (24, 48, 72),
 '27210': (24, 63, 87),
 '28212': (24, 41, 65),
 '99250': (0, 94, 94),
 '99252': (35, 55, 90),
 '27254': (37, 54, 91),
 '27256': (36, 55, 91),
 '28256': (36, 56, 92),
 '27258': (35, 50, 85),
 '27301': (22, 46, 68),
 '98301': (24, 66, 90),
 '27303': (25, 37, 62),
 '28303': (25, 40, 65),
 '27307': (25, 61, 86),
 '99311': (23, 65, 88),
 '27351': (38, 55, 93),
 '98351': (38, 55, 93),
 '27353': (39, 57, 96),
 '27357': (38, 56, 94),
 '28357': (38, 58, 96),
 '27359': (39, 58, 97),
 '27302': (25, 57, 82),
 '27304': (24, 50, 74),
 '27306': (25, 60, 85),
 '27308': (24, 59, 83),
 '27310': (21, 53, 74),
 '49310': (25, 53, 78),
 '27352': (37, 54, 91),
 '27354': (38, 53, 91),
 '27356': (38, 55, 93),
 '49358': (40, 59, 99),
 'sems': [3, 4, 5, 6],
 'tot1': 0,
 'totw1': 0,
 'ns1': 0,
 'nsw1': 0,
 'tot2': 0,
 'totw2': 0,
 'ns2': 0,
 'nsw2': 0,
 'tot3': 778,
 'totw3': 2071,
 'ns3': 10,
 'nsw3': 28,
 'tot4': 972,
 'totw4': 2172,
 'ns4': 12,
 'nsw4': 29,
 'tot5': 1028,
 'totw5': 2047,
 'ns5': 12,
 'nsw5': 26,
 'tot6': 850,
 'totw6': 2195,
 'ns6': 10,
 'nsw6': 27,
 'tot7': 0,
 'totw7': 0,
 'ns7': 0,
 'nsw7': 0,
 'tot8': 0,
 'totw8': 0,
 'ns8': 0,
 'nsw8': 0}

### Connecting to MongoDB Atlas

In [10]:
import pymongo

client = pymongo.MongoClient("mongodb+srv://xxx:xxx@cluster0-gclx4.mongodb.net/test?retryWrites=true&w=majority")
db = client.test

##### Inserting all the records from studentwise into the database

In [11]:
ret = db.test.insert_many(studentwise)

In [12]:
db.test.find_one({'name':'Sharat Sachin'})

{'_id': ObjectId('5d5577cfef04e6ea4de59a14'),
 'en_no': '03111502716',
 'name': 'Sharat Sachin',
 'college': 'BVCOE',
 'batch': 2016,
 'class': 115,
 'course': 27,
 '99101': [22, 61, 83],
 '99103': [24, 48, 72],
 '36105': [21, 48, 69],
 '49107': [19, 37, 56],
 '98109': [0, 86, 86],
 '27111': [21, 55, 76],
 '99113': [23, 55, 78],
 '99151': [37, 56, 93],
 '49153': [35, 46, 81],
 '36155': [37, 44, 81],
 '27157': [37, 48, 85],
 '36157': [38, 46, 84],
 '99161': [36, 53, 89],
 '99102': [17, 65, 82],
 '99104': [21, 71, 92],
 '28106': [19, 72, 91],
 '27108': [21, 65, 86],
 '36110': [22, 63, 85],
 '98112': [20, 65, 85],
 '56114': [20, 61, 81],
 '99152': [37, 54, 91],
 '27154': [36, 54, 90],
 '28156': [37, 57, 94],
 '36158': [39, 44, 83],
 '56160': [37, 57, 94],
 '99201': [21, 24, 45],
 '27203': [22, 61, 83],
 '28205': [19, 51, 70],
 '49207': [20, 51, 71],
 '27209': [24, 54, 78],
 '27211': [17, 46, 63],
 '28253': [34, 53, 87],
 '27255': [36, 53, 89],
 '27257': [35, 48, 83],
 '49257': [37, 41, 78],
 '99202': [17, 60, 77],
 '27204': [20, 52, 72],
 '27206': [23, 55, 78],
 '27208': [20, 55, 75],
 '27210': [22, 42, 64],
 '28212': [20, 41, 61],
 '99250': [0, 83, 83],
 '99252': [37, 48, 85],
 '27254': [32, 48, 80],
 '27256': [33, 53, 86],
 '28256': [37, 48, 85],
 '27258': [34, 50, 84],
 '27301': [19, 47, 66],
 '98301': [23, 55, 78],
 '27303': [17, 68, 85],
 '28303': [19, 66, 85],
 '27307': [24, 50, 74],
 '99311': [24, 51, 75],
 '27351': [37, 45, 82],
 '98351': [32, 50, 82],
 '27353': [37, 50, 87],
 '27357': [34, 54, 88],
 '28357': [34, 50, 84],
 '27359': [32, 52, 84],
 '27302': [19, 69, 88],
 '27304': [22, 50, 72],
 '27306': [19, 60, 79],
 '27308': [21, 61, 82],
 '27310': [22, 52, 74],
 '49310': [16, 51, 67],
 '27352': [37, 52, 89],
 '27354': [35, 58, 93],
 '27356': [37, 52, 89],
 '49358': [37, 55, 92],
 'sems': [1, 2, 3, 4, 5, 6],
 'tot1': 1033,
 'totw1': 2073,
 'ns1': 13,
 'nsw1': 27,
 'tot2': 1054,
 'totw2': 2340,
 'ns2': 12,
 'nsw2': 27,
 'tot3': 747,
 'totw3': 1977,
 'ns3': 10,
 'nsw3': 28,
 'tot4': 930,
 'totw4': 2147,
 'ns4': 12,
 'nsw4': 29,
 'tot5': 970,
 'totw5': 2050,
 'ns5': 12,
 'nsw5': 26,
 'tot6': 825,
 'totw6': 2129,
 'ns6': 10,
 'nsw6': 27,
 'tot7': 0,
 'totw7': 0,
 'ns7': 0,
 'nsw7': 0,
 'tot8': 0,
 'totw8': 0,
 'ns8': 0,
 'nsw8': 0}